FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY *.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Docker -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
RUN mkdir -p /app/certificates
COPY --from=build /app/publish .
EXPOSE 5074 5075
ENV ASPNETCORE_ENVIRONMENT=Production
ENTRYPOINT ["dotnet", "DNSApi.dll"]